### ISSUE TITLE
Enable detection of custom deployment CRD's (argo-rollouts)

### ISSUE THREAD

**Issue by Temikus** [castai/k8s-agent#81]
We use some custom deployment CRD’s (argo rollouts - Rollout) to drive our workloads - is it possible to include those into cost reporting? They answer to all the same API’s as Deployment does - they’re just an extension.

Here's a spec: https://argoproj.github.io/argo-rollouts/features/specification/

Minimal example:
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
```
